In [2]:
import pandas as pd 
icing_features = pd.read_csv('E:/PycharmProjects/AI/icing_residuals.csv')
icing_features

       Unnamed: 0  yaw_position  pitch2_moto_tmp   int_tmp  environment_tmp
0               0     -0.000491        -0.008481 -0.029340        -0.019949
1               1     -0.001851        -0.008831 -0.029263        -0.020527
2               2     -0.002836        -0.009290 -0.028715        -0.020975
3               3     -0.003342        -0.009818 -0.027661        -0.021200
4               4     -0.003295        -0.010364 -0.026078        -0.021060
...           ...           ...              ...       ...              ...
11995       11995      0.023111         0.112226  0.198152         0.171596
11996       11996      0.022341         0.112046  0.197964         0.170290
11997       11997      0.021576         0.112362  0.197340         0.169189
11998       11998      0.020846         0.113082  0.196331         0.168337
11999       11999      0.020166         0.114095  0.195015         0.167743

[12000 rows x 5 columns]

In [4]:
import numpy as np 
n = len(icing_features)
tm, tp, tpp, te, tr = np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n)
for i in range(n):
    data = np.array(icing_features['yaw_position'][i:i+10])
    tm[i] = np.sum(data)/10
    tp[i] = np.max(data)
    tpp[i] = np.subtract(np.max(data),np.min(data))
    te[i] = np.sum(np.square(data))
    tr[i] = (np.sum(np.sqrt(np.abs(data)))/10)**2
tm

array([-8.40071056e-04, -4.72461191e-05,  1.13568809e-03, ...,
        6.25871001e-03,  4.10115755e-03,  2.01658036e-03])

In [5]:
f1 = np.vstack((tm,tp,tpp,te,tr)).T
f1.shape

(12000, 5)

In [6]:
tm, tp, tpp, te, tr = np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n)
for i in range(n):
    data = np.array(icing_features['pitch2_moto_tmp'][i:i+10])
    tm[i] = np.sum(data)/10
    tp[i] = np.max(data)
    tpp[i] = np.subtract(np.max(data),np.min(data))
    te[i] = np.sum(np.square(data))
    tr[i] = (np.sum(np.sqrt(np.abs(data)))/10)**2
tm

array([-0.01040625, -0.01072666, -0.01100108, ...,  0.03395394,
        0.02271773,  0.01140953])

In [7]:
f2 = np.vstack((tm,tp,tpp,te,tr)).T
f2.shape

(12000, 5)

In [8]:
tm, tp, tpp, te, tr = np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n)
for i in range(n):
    data = np.array(icing_features['int_tmp'][i:i+10])
    tm[i] = np.sum(data)/10
    tp[i] = np.max(data)
    tpp[i] = np.subtract(np.max(data),np.min(data))
    te[i] = np.sum(np.square(data))
    tr[i] = (np.sum(np.sqrt(np.abs(data)))/10)**2
tm

array([-0.02295541, -0.02065642, -0.01794483, ...,  0.05886861,
        0.03913465,  0.0195015 ])

In [9]:
f3 = np.vstack((tm,tp,tpp,te,tr)).T
f3.shape

(12000, 5)

In [10]:
tm, tp, tpp, te, tr = np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n),np.zeros(n)
for i in range(n):
    data = np.array(icing_features['environment_tmp'][i:i+10])
    tm[i] = np.sum(data)/10
    tp[i] = np.max(data)
    tpp[i] = np.subtract(np.max(data),np.min(data))
    te[i] = np.sum(np.square(data))
    tr[i] = (np.sum(np.sqrt(np.abs(data)))/10)**2
tm

array([-0.01812712, -0.01646172, -0.0141521 , ...,  0.05052698,
        0.03360807,  0.01677434])

In [11]:
f4 = np.vstack((tm,tp,tpp,te,tr)).T
f4.shape

(12000, 5)

In [12]:
features = np.concatenate((f1,f2,f3,f4),axis=1)
features = pd.DataFrame(features)
features

             0         1         2   ...        17        18        19
0     -0.000840  0.004858  0.008199  ...  0.012569  0.003445  0.017857
1     -0.000047  0.007438  0.010779  ...  0.017905  0.003058  0.015687
2      0.001136  0.009978  0.013320  ...  0.023769  0.002643  0.013453
3      0.002649  0.012300  0.015642  ...  0.029688  0.002275  0.012259
4      0.004407  0.014231  0.017526  ...  0.034969  0.002019  0.011654
...         ...       ...       ...  ...       ...       ...       ...
11995  0.010804  0.023111  0.002946  ...  0.003853  0.143544  0.042357
11996  0.008493  0.022341  0.002175  ...  0.002546  0.114099  0.027022
11997  0.006259  0.021576  0.001410  ...  0.001446  0.085100  0.015158
11998  0.004101  0.020846  0.000680  ...  0.000594  0.056475  0.006722
11999  0.002017  0.020166  0.000000  ...  0.000000  0.028138  0.001677

[12000 rows x 20 columns]

In [15]:
features.to_csv('E:/PycharmProjects/AI/icing_features.csv')